version: "3.3"
services:
  policyEngine:
    image: "christianhugo/policy-engine:latest"
    network_mode: "host"
    depends_on:
      - "mongoDB"
      - "localIdp"
  nginx:
    image: "christianhugo/policy-dashboard:latest"
    network_mode: "host"
  mongoDB:
    image: "mongo:latest"
    command: ["mongod", "--auth"]
    environment:
      MONGO_INITDB_DATABASE: policy_system
    ports:
      - "27017:27017"
    volumes:
      - ./cfg/mongo/db_init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  localIdp:
    image: "christianhugo/local-idp:latest"
    ports:
      - "3333:3333"
